package models

// ISO 639-1 language code constants for ergonomic SDK usage.
const (
	LanguageEnglish          = "en"
	LanguageFrench           = "fr"
	LanguageSpanish          = "es"
	LanguageGerman           = "de"
	LanguageItalian          = "it"
	LanguagePortuguese       = "pt"
	LanguageRussian          = "ru"
	LanguageJapanese         = "ja"
	LanguageChinese          = "zh"
	LanguageKorean           = "ko"
	LanguageArabic           = "ar"
	LanguageDutch            = "nl"
	LanguageSwedish          = "sv"
	LanguageNorwegian        = "no"
	LanguageDanish           = "da"
	LanguageFinnish          = "fi"
	LanguagePolish           = "pl"
	LanguageTurkish          = "tr"
	LanguageGreek            = "el"
	LanguageHebrew           = "he"
	LanguageHindi            = "hi"
	LanguageThai             = "th"
	LanguageVietnamese       = "vi"
	LanguageIndonesian       = "id"
	LanguageCzech            = "cs"
	LanguageRomanian         = "ro"
	LanguageHungarian        = "hu"
	LanguageBulgarian        = "bg"
	LanguageCroatian         = "hr"
	LanguageSlovak           = "sk"
	LanguageSlovenian        = "sl"
	LanguageUkrainian        = "uk"
	LanguageNorwegianBokmal  = "nb"
	LanguageNorwegianNynorsk = "nn"
)
